// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsd-e7zla5HxwvyKhBTQmXM1sLaJSktdo',
    appId: '1:77034133665:web:d210989732be70908d78e0',
    messagingSenderId: '77034133665',
    projectId: 'newsapp-3d12b',
    authDomain: 'newsapp-3d12b.firebaseapp.com',
    storageBucket: 'newsapp-3d12b.appspot.com',
    measurementId: 'G-BER3FL8N6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAOVilOlVnrwOa5Kvq3y5roY4Ne-vEVKA',
    appId: '1:77034133665:android:7d3229342a9736f98d78e0',
    messagingSenderId: '77034133665',
    projectId: 'newsapp-3d12b',
    storageBucket: 'newsapp-3d12b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAI85t_1CZTHZAb46Y-iLuXJKc6bALWw8',
    appId: '1:77034133665:ios:c64db10950e8e5848d78e0',
    messagingSenderId: '77034133665',
    projectId: 'newsapp-3d12b',
    storageBucket: 'newsapp-3d12b.appspot.com',
    androidClientId: '77034133665-barfks56tdo33g51dhgc7ci1v4obsqt2.apps.googleusercontent.com',
    iosClientId: '77034133665-pnsle8vr2nqnsp854lf814pr6e8pc9su.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAI85t_1CZTHZAb46Y-iLuXJKc6bALWw8',
    appId: '1:77034133665:ios:c64db10950e8e5848d78e0',
    messagingSenderId: '77034133665',
    projectId: 'newsapp-3d12b',
    storageBucket: 'newsapp-3d12b.appspot.com',
    androidClientId: '77034133665-barfks56tdo33g51dhgc7ci1v4obsqt2.apps.googleusercontent.com',
    iosClientId: '77034133665-pnsle8vr2nqnsp854lf814pr6e8pc9su.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );
}
